language: go
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_150e64d3bf53_key -iv $encrypted_150e64d3bf53_iv
  -in secrets.tar.enc -out operations/secrets.tar -d
- tar -xvf operations/secrets.tar -C operations
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make ci
before_deploy:
- nvm install node
- cd operations/scripts; npm install; cd ../../
deploy:
- provider: script
  script: "./operations/scripts/deploy.js --branch $TRAVIS_BRANCH --env testing"
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: "./operations/scripts/deploy.js --branch $TRAVIS_BRANCH --env staging"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: "./operations/scripts/deploy.js --tag $TRAVIS_TAG --env production"
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: NBfWSSnKkTV+xCifjYyqUOorMUkyIWBzwMhbE3qkCa9tWyGcLYnSi2aJrenczXFi1cU+ji1UNiwrD6iiE7NUGrkaj1+ZQh/aZlg3ifiTd9/pCEzLdLQXL7SL0syEM2JqByo7wlUJ+F3nKJxKYO+fEM3vcK4CO0HdvmvixQiZKKghMBUvsFOB00+P87tnrBLQkaJfdda6IluhhgBFvtm5+VZFG6RXDzWfOIlYT+hdo/oegqlu4MWjVXy1ntx1RwgubkkG/ESGgq7zrsIaAgqz93QJegAM5+v3ulhFpVmChbniy5kX907E3r8VEifXJ0hy1bfeh/SuJNsEfghDGLNJHprF9hZ8R2eTewKGp+pmj12iUF+l4xkUiz4v5q5l8z9GZiPHHnq+nsYY1U1zl4MHVPyndVHFzYn2DLzhYg3bKxFgyxWkfWsjBmd087moM297moeS6bQLp2JMifijys18hPOxOg81cMZ7cjYhaLlpg7WTMVccnzkIzdfvJMcjw2fmriUAuUb+RS5wDv+pkbkgW2enRtH3dQM4s4INRFiv1brfK4CF23N/R/dqJf+QzPTCYVlbOw/A3mvuRFlZKIxCy0ulxd7x9gOsd1DDoJ6ENqRx9CekgHF9hJBhMCO3JM5oy5NcvQez2sEFq7ekvs6a6pD0+9NcQirQdAH8q5zpcQY=
env:
  global:
  - secure: lOmgunGNbGSJPoSbALRFQ5W3ujfR7qubNjsaCsEdOP1cPpKEAlpV+nHe/ObrTYWFEbpvFa0o+0inqzpiu0OjldkF/JoQuajmfMBjalb1Db8WJ3GxJ9ghh1WtF3yszU9qPhmy+4/Bg92D7YKzyMgC7YSvcOc/i0xKpWZO0zdV+7IoFpwdao2aXQLkrgO801e7Mu8JWbG27QOEHZ4smf7raEIQDfoZBx5VehL7y1S1meZVpppRWE1B79n/dqSbg8N77bfuoiIjquKvcT8OqNJ1pOouLqfzU0WT7djzZ2NA+RVx/jrNO3vCacFXifXHm31Ny5W9/a9kGTzfzlF54yGbBsqtwDkzQ5PCBrXfhXJkRflJcJaiWZF6f+QuyTEDo+uo6c+5lHn/PH+MPkg+aFicOAmDAEfPbWOms0uNb18QuDWYMupBGzGpj/SbrnOIRf7Byw56SULxnUr6QAjNyt7V+HYZMPNRFk8aZZop9tli+KIVb3YtkIECxuN+N5b0G0zo/DXGrA120lT910wL+/2Zy6LvTD8J2aLbzscmc9teZOJuE4IjyGFdkqN8asL2nMr3OhbHvNCKEssoZG3EVZeYUNAACGKgSVkZHeuQRrb2uj+dHc8M1iexkwLZGiWzYfeshCuZyxs5q0NCMurMlOGMX1xyWfqMH/qVEfM6Cj7xo0Q=
  - secure: s9EJqqmQ2elJjTG7TJ05iSt3szqKUV8m7K7J5WLbHFnZLG9Flkuk+jiWMXVZpe/Bje8GlDDLmGsYrELmjOWfL3Dizk7cw++tIeju0k9FnznE5zZ981B5Ay7ZyYtDU5JOS66264y4L+v9sgwT0DpHdBQwraUFlPb48HzqxwF9tit5atTrPaGiE9Dt4Dq5XeyeIPKjWGKDOCVcHu+MH44O+umS8idffy2tqQVyVk+5OXApUYDTmmv2vJkj67AjqvqEMTLhpODuzjA3SyoxK41RiVSFOQTnVpVbOhQxJ4IyRSKm3yBUCzjIDKkQSmxg3xlbZr4yFUl/3su1NvTU9h/CrIkz7XuQuxxB87vDy/jAT/Ac3Xk9ZHhPqVyhzMjyg60bw+F0fOFO4vXXpyhG37wfHMSPtJ5Ttpe5Cmq4gOMw3ZWjMLufF/9HkcEYpYdZbKK9QdgkUg2yGtAWb6+SqNjZG66YWYJhib2unMWY+q8jrI0JN669yVRFV/ibo1U3lzw4bjtD9yRVH5lU32nDkzgOpqPVY5gHQ/eABFlMjJrFWpB0oBe2oHL7bKpPdaXsM97E3OsaG4vMCjvqWnV/u2qEa3FGfrwFMoPf6WnguL8pYqGuJ2vtiqwyzHnzHalld8XkEa8AeUMjr3ffl6NBQw073dZUeFtMvww+P0NkuzdB5tk=
  - secure: vq33eOFZWq683IPdvRxwbHUnEX6y29Q6bq7XLjib1PhPCh1p1OOSppNru5O6Za8kuGZfHuvNJYHEjwXv5xIUpKxa8O7mgSmSEgEQlmS5wGOBkXtST1JBcwZEomk/i5PflGumuom+Gm75IlD8hmv0E7F+gB87DN1tO93PgzdxshHZA1Vids3iyEBg3ekCBWN5fyIqlKpbWxdA4XtR7Lo+aw6hOg6uk59uFN1e7+1ZsT9Wyu7b7FmiR4qDF+4wV4JRgjKB/KJYybC7K2Ey4aCz70aGo3LcbeL4HvG3/B1SWqKQTDNXQYRkAgzg37A7U5YSzNr8Iw1SLKhvK2AiSsBrosKVAaa+Z5lwK2LH0eQ+L6caazHgJDerxy5oX7g7dMFjy/P2E/uTBTQm4HDg9+jvSmG5vYfsvAAMaqYAS0d68d0FBKliXpv74mr2Ee9RiXWwaUrPJFTnIH+YR65bGtNgFD6/O9XeaIE6VJomnBpaoSXBiywK1o3jsAMP2dQQz+U4fIk6WLO6P5wG2Eeb2qEqfMEKdO3Ds4YKXYXJgmK4aHi251i2EAce6Es6/oQNkkBhoKBYhwlqyusRbcQ5gRW32IztSdTEHdGKfUEKiwfhL2UU7Mgi09zH4HuAaQbulcD6EbSbHTqhPaTkkodHl6/9SGCe7C2Ma64uZ4N/zqqSCy8=
