version: "3"

services: 
  api:
    build:
      context: .
      dockerfile: operations/docker/Dockerfile.dev
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
    volumes: 
      - ".:/go/src/github.com/badmuts/hsleiden-ipsenh-api"
    
  db:
    image: mongo:3.4
    ports:
      - "27017:27017"
      