# Base this docker container off the official golang docker image.
# Docker containers inherit everything from their base.
FROM golang:1.8.0
# Create a directory inside the container to store all our application and then make it the working directory.
RUN mkdir -p /go/src/github.com/badmuts/hsleiden-ipsenh-api
WORKDIR /go/src/github.com/badmuts/hsleiden-ipsenh-api
# Copy the hsleiden-ipsenh-api directory (where the Dockerfile lives) into the container.
COPY . /go/src/github.com/badmuts/hsleiden-ipsenh-api

# Download and install any required third party dependencies into the container.
RUN go get -u github.com/golang/lint/golint
RUN curl https://glide.sh/get | sh
RUN glide install